project:
  type: website
  output-dir: docs

website:
  favicon: logo.png
  back-to-top-navigation: true
  title: "Egoitz's Page"
  navbar:
    logo: icono_barra.png
    right:
      - text: "Home"
        file: index.qmd
      - text: "TidyTuesday"
        file: "tidytuesday/index.qmd"
      - text: "Archive"
        file: archive.qmd
      - about.qmd
      - icon: github
        href: https://github.com/Egoitzct
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

